/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import oop.Akun;
import oop.Login;
import oop.Register;

/**
 *
 * @author User
 */
public class HalamanLogin extends javax.swing.JFrame {

    /**
     * Creates new form HalamanLogin
     */
    private final DateFormat formatTanggal = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
    private final Date tanggal = new Date();
    
    private Akun akun;
    private Register register;
    private Login login;
   
    public HalamanLogin() {
        initComponents();
        layerLoginAdmin.setVisible(false);
        layerRegisterAdmin.setVisible(false);
        layerLoginCustomer.setVisible(false);
        layerRegisterCustomer.setVisible(false);
        addPlaceholderStyle(emailLoginAdmin);
        addPlaceholderStyle(passwordLoginAdmin);
        addPlaceholderStyle(emailRegisterAdmin);
        addPlaceholderStyle(passwordRegisterAdmin);
        addPlaceholderStyle(namaRegisterAdmin);
        addPlaceholderStyle(namaRegisterCustomer);
        addPlaceholderStyle(emailLoginCustomer);
        addPlaceholderStyle(passwordLoginCustomer);
        addPlaceholderStyle(emailRegisterCustomer);
        addPlaceholderStyle(passwordRegisterCustomer);
    }

    public void addPlaceholderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.BLACK);
    }
    
    public void removePlaceholderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activity = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        layerActivity = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectAdmin = new javax.swing.JButton();
        selectCustomer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        layerLoginAdmin = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        emailLoginAdmin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        passwordLoginAdmin = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        loginAdmin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        registerNowAdmin = new javax.swing.JLabel();
        backLoginAdmin = new javax.swing.JButton();
        layerRegisterAdmin = new javax.swing.JLayeredPane();
        jPanel7 = new javax.swing.JPanel();
        namaRegisterAdmin = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        emailRegisterAdmin = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        passwordRegisterAdmin = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        registerAdmin = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        loginNowAdmin = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        layerLoginCustomer = new javax.swing.JLayeredPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        emailLoginCustomer = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        passwordLoginCustomer = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        loginCustomer = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        registerNowCustomer = new javax.swing.JLabel();
        backLoginCustomer = new javax.swing.JButton();
        layerRegisterCustomer = new javax.swing.JLayeredPane();
        jPanel9 = new javax.swing.JPanel();
        namaRegisterCustomer = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        emailRegisterCustomer = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        passwordRegisterCustomer = new javax.swing.JPasswordField();
        jLabel28 = new javax.swing.JLabel();
        RegisterCustomer = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        loginNowCustomer = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activity.setBackground(new java.awt.Color(255, 255, 255));
        activity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        activity.setMaximumSize(new java.awt.Dimension(277, 371));
        activity.setMinimumSize(new java.awt.Dimension(277, 371));
        activity.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/komputer.png"))); // NOI18N
        activity.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 290, 250));

        layerActivity.setMaximumSize(new java.awt.Dimension(277, 371));
        layerActivity.setMinimumSize(new java.awt.Dimension(277, 371));
        layerActivity.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel4.setMaximumSize(new java.awt.Dimension(277, 371));
        jPanel4.setMinimumSize(new java.awt.Dimension(277, 371));
        jPanel4.setPreferredSize(new java.awt.Dimension(277, 371));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Activity");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 46));

        selectAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectAdmin.setText("ADMIN");
        selectAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAdminActionPerformed(evt);
            }
        });
        jPanel4.add(selectAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 170, 25));

        selectCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectCustomer.setText("CUSTOMER");
        selectCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCustomerActionPerformed(evt);
            }
        });
        jPanel4.add(selectCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 170, 25));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        layerActivity.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        activity.add(layerActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 310, -1));

        layerLoginAdmin.setMaximumSize(new java.awt.Dimension(277, 371));
        layerLoginAdmin.setMinimumSize(new java.awt.Dimension(277, 371));
        layerLoginAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.setMaximumSize(new java.awt.Dimension(277, 371));
        jPanel5.setMinimumSize(new java.awt.Dimension(277, 371));
        jPanel5.setPreferredSize(new java.awt.Dimension(277, 371));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Login Admin");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 46));

        emailLoginAdmin.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailLoginAdmin.setText("Email");
        emailLoginAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailLoginAdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailLoginAdminFocusLost(evt);
            }
        });
        jPanel5.add(emailLoginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 25));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        passwordLoginAdmin.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        passwordLoginAdmin.setText("Password");
        passwordLoginAdmin.setEchoChar('\u0000');
        passwordLoginAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLoginAdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordLoginAdminFocusLost(evt);
            }
        });
        jPanel5.add(passwordLoginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 180, 25));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        loginAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginAdmin.setText("Login");
        loginAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        loginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAdminActionPerformed(evt);
            }
        });
        jPanel5.add(loginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 210, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("dont't have an account?");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 320, -1, -1));

        registerNowAdmin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        registerNowAdmin.setForeground(new java.awt.Color(0, 51, 255));
        registerNowAdmin.setText("Register Now");
        registerNowAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerNowAdminMouseClicked(evt);
            }
        });
        jPanel5.add(registerNowAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        backLoginAdmin.setBackground(new java.awt.Color(0, 204, 153));
        backLoginAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        backLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginAdminActionPerformed(evt);
            }
        });
        jPanel5.add(backLoginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        layerLoginAdmin.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        activity.add(layerLoginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 310, -1));

        layerRegisterAdmin.setMaximumSize(new java.awt.Dimension(277, 371));
        layerRegisterAdmin.setMinimumSize(new java.awt.Dimension(277, 371));
        layerRegisterAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 204, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel7.setMaximumSize(new java.awt.Dimension(277, 371));
        jPanel7.setMinimumSize(new java.awt.Dimension(277, 371));
        jPanel7.setPreferredSize(new java.awt.Dimension(277, 371));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaRegisterAdmin.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        namaRegisterAdmin.setText("Nama Lengkap");
        namaRegisterAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaRegisterAdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaRegisterAdminFocusLost(evt);
            }
        });
        jPanel7.add(namaRegisterAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 180, 25));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Register Admin");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 46));

        emailRegisterAdmin.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailRegisterAdmin.setText("Email");
        emailRegisterAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailRegisterAdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailRegisterAdminFocusLost(evt);
            }
        });
        jPanel7.add(emailRegisterAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 25));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        passwordRegisterAdmin.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        passwordRegisterAdmin.setText("Password");
        passwordRegisterAdmin.setEchoChar('\u0000');
        passwordRegisterAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRegisterAdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordRegisterAdminFocusLost(evt);
            }
        });
        jPanel7.add(passwordRegisterAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 180, 25));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        registerAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerAdmin.setText("Register");
        registerAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        registerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerAdminActionPerformed(evt);
            }
        });
        jPanel7.add(registerAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, 25));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel18.setText("already have an account?");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        loginNowAdmin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        loginNowAdmin.setForeground(new java.awt.Color(0, 51, 255));
        loginNowAdmin.setText("login now");
        loginNowAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginNowAdminMouseClicked(evt);
            }
        });
        jPanel7.add(loginNowAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        layerRegisterAdmin.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        activity.add(layerRegisterAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 310, -1));

        layerLoginCustomer.setMaximumSize(new java.awt.Dimension(277, 371));
        layerLoginCustomer.setMinimumSize(new java.awt.Dimension(277, 371));
        layerLoginCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 204, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel8.setMaximumSize(new java.awt.Dimension(277, 371));
        jPanel8.setMinimumSize(new java.awt.Dimension(277, 371));
        jPanel8.setPreferredSize(new java.awt.Dimension(277, 371));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Login Customer");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 46));

        emailLoginCustomer.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailLoginCustomer.setText("Email");
        emailLoginCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailLoginCustomerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailLoginCustomerFocusLost(evt);
            }
        });
        jPanel8.add(emailLoginCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 25));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        passwordLoginCustomer.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        passwordLoginCustomer.setText("Password");
        passwordLoginCustomer.setEchoChar('\u0000');
        passwordLoginCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLoginCustomerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordLoginCustomerFocusLost(evt);
            }
        });
        jPanel8.add(passwordLoginCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 180, 25));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        loginCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginCustomer.setText("Login");
        loginCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        loginCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCustomerActionPerformed(evt);
            }
        });
        jPanel8.add(loginCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 210, 25));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel24.setText("dont't have an account?");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 320, -1, -1));

        registerNowCustomer.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        registerNowCustomer.setForeground(new java.awt.Color(0, 51, 255));
        registerNowCustomer.setText("Register Now");
        registerNowCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerNowCustomerMouseClicked(evt);
            }
        });
        jPanel8.add(registerNowCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        backLoginCustomer.setBackground(new java.awt.Color(0, 204, 153));
        backLoginCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        backLoginCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginCustomerActionPerformed(evt);
            }
        });
        jPanel8.add(backLoginCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        layerLoginCustomer.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        activity.add(layerLoginCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 310, -1));

        layerRegisterCustomer.setMaximumSize(new java.awt.Dimension(277, 371));
        layerRegisterCustomer.setMinimumSize(new java.awt.Dimension(277, 371));
        layerRegisterCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 204, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel9.setMaximumSize(new java.awt.Dimension(277, 371));
        jPanel9.setMinimumSize(new java.awt.Dimension(277, 371));
        jPanel9.setPreferredSize(new java.awt.Dimension(277, 371));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaRegisterCustomer.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        namaRegisterCustomer.setText("Nama Lengkap");
        namaRegisterCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaRegisterCustomerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaRegisterCustomerFocusLost(evt);
            }
        });
        jPanel9.add(namaRegisterCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 180, 25));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Register Customer");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 46));

        emailRegisterCustomer.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailRegisterCustomer.setText("Email");
        emailRegisterCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailRegisterCustomerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailRegisterCustomerFocusLost(evt);
            }
        });
        jPanel9.add(emailRegisterCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 25));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        passwordRegisterCustomer.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        passwordRegisterCustomer.setText("Password");
        passwordRegisterCustomer.setEchoChar('\u0000');
        passwordRegisterCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRegisterCustomerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordRegisterCustomerFocusLost(evt);
            }
        });
        jPanel9.add(passwordRegisterCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 180, 25));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        RegisterCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisterCustomer.setText("Register");
        RegisterCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        RegisterCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerActionPerformed(evt);
            }
        });
        jPanel9.add(RegisterCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, 25));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel29.setText("already have an account?");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        loginNowCustomer.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        loginNowCustomer.setForeground(new java.awt.Color(0, 51, 255));
        loginNowCustomer.setText("login now");
        loginNowCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginNowCustomerMouseClicked(evt);
            }
        });
        jPanel9.add(loginNowCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        layerRegisterCustomer.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        activity.add(layerRegisterCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 310, -1));

        getContentPane().add(activity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCustomerActionPerformed
        // TODO add your handling code here:
        layerActivity.setVisible(false);
        layerLoginAdmin.setVisible(false);
        layerRegisterAdmin.setVisible(false);
        layerLoginCustomer.setVisible(true);
        layerRegisterCustomer.setVisible(false);
    }//GEN-LAST:event_selectCustomerActionPerformed

    private void selectAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAdminActionPerformed
        // TODO add your handling code here:
        layerActivity.setVisible(false);
        layerLoginAdmin.setVisible(true);
        layerRegisterAdmin.setVisible(false);
        layerLoginCustomer.setVisible(false);
        layerRegisterCustomer.setVisible(false);

    }//GEN-LAST:event_selectAdminActionPerformed

    private void registerNowAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerNowAdminMouseClicked
        // TODO add your handling code here:
        layerActivity.setVisible(false);
        layerLoginAdmin.setVisible(false);
        layerRegisterAdmin.setVisible(true);
        layerLoginCustomer.setVisible(false);
        layerRegisterCustomer.setVisible(false);
    }//GEN-LAST:event_registerNowAdminMouseClicked

    private void loginNowAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNowAdminMouseClicked
        // TODO add your handling code here:
        layerActivity.setVisible(false);
        layerLoginAdmin.setVisible(true);
        layerRegisterAdmin.setVisible(false);
        layerLoginCustomer.setVisible(false);
        layerRegisterCustomer.setVisible(false);
    }//GEN-LAST:event_loginNowAdminMouseClicked

    private void registerNowCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerNowCustomerMouseClicked
        // TODO add your handling code here:
        layerActivity.setVisible(false);
        layerLoginAdmin.setVisible(false);
        layerRegisterAdmin.setVisible(false);
        layerLoginCustomer.setVisible(false);
        layerRegisterCustomer.setVisible(true);
    }//GEN-LAST:event_registerNowCustomerMouseClicked

    private void loginNowCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNowCustomerMouseClicked
        // TODO add your handling code here:
        layerActivity.setVisible(false);
        layerLoginAdmin.setVisible(false);
        layerRegisterAdmin.setVisible(false);
        layerLoginCustomer.setVisible(true);
        layerRegisterCustomer.setVisible(false);
    }//GEN-LAST:event_loginNowCustomerMouseClicked

    private void emailLoginAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailLoginAdminFocusGained
        // TODO add your handling code here:
        if (emailLoginAdmin.getText().equals("Email")) {
            emailLoginAdmin.setText("");
            emailLoginAdmin.requestFocus();
            removePlaceholderStyle(emailLoginAdmin);
        }
    }//GEN-LAST:event_emailLoginAdminFocusGained

    private void emailLoginAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailLoginAdminFocusLost
        // TODO add your handling code here:
        if (emailLoginAdmin.getText().length() == 0) {
            addPlaceholderStyle(emailLoginAdmin);
            emailLoginAdmin.setText("Email");
        }
    }//GEN-LAST:event_emailLoginAdminFocusLost

    private void passwordLoginAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginAdminFocusGained
        // TODO add your handling code here:
        if (passwordLoginAdmin.getText().equals("Password")) {
            passwordLoginAdmin.setText("");
            passwordLoginAdmin.requestFocus();
            passwordLoginAdmin.setEchoChar('*');
            removePlaceholderStyle(passwordLoginAdmin);
        }
    }//GEN-LAST:event_passwordLoginAdminFocusGained

    private void passwordLoginAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginAdminFocusLost
        // TODO add your handling code here:
        if (passwordLoginAdmin.getText().length() == 0) {
            addPlaceholderStyle(passwordLoginAdmin);
            passwordLoginAdmin.setText("Password");
            passwordLoginAdmin.setEchoChar((char)0);
        }
    }//GEN-LAST:event_passwordLoginAdminFocusLost

    private void backLoginCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginCustomerActionPerformed
        // TODO add your handling code here:
        layerActivity.setVisible(true);
        layerLoginAdmin.setVisible(false);
        layerRegisterAdmin.setVisible(false);
        layerLoginCustomer.setVisible(false);
        layerRegisterCustomer.setVisible(false);
    }//GEN-LAST:event_backLoginCustomerActionPerformed

    private void backLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginAdminActionPerformed
        // TODO add your handling code here:
        layerActivity.setVisible(true);
        layerLoginAdmin.setVisible(false);
        layerRegisterAdmin.setVisible(false);
        layerLoginCustomer.setVisible(false);
        layerRegisterCustomer.setVisible(false);
    }//GEN-LAST:event_backLoginAdminActionPerformed

    private void namaRegisterAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaRegisterAdminFocusGained
        // TODO add your handling code here:
        if (namaRegisterAdmin.getText().equals("Nama Lengkap")) {
            namaRegisterAdmin.setText("");
            namaRegisterAdmin.requestFocus();
            removePlaceholderStyle(namaRegisterAdmin);
        }
    }//GEN-LAST:event_namaRegisterAdminFocusGained

    private void namaRegisterAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaRegisterAdminFocusLost
        // TODO add your handling code here:
        if (namaRegisterAdmin.getText().length() == 0) {
            addPlaceholderStyle(namaRegisterAdmin);
            namaRegisterAdmin.setText("Nama Lengkap");
        }
    }//GEN-LAST:event_namaRegisterAdminFocusLost

    private void emailRegisterAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailRegisterAdminFocusGained
        // TODO add your handling code here:
        if (emailRegisterAdmin.getText().equals("Email")) {
            emailRegisterAdmin.setText("");
            emailRegisterAdmin.requestFocus();
            removePlaceholderStyle(emailRegisterAdmin);
        }
    }//GEN-LAST:event_emailRegisterAdminFocusGained

    private void emailRegisterAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailRegisterAdminFocusLost
        // TODO add your handling code here:
        if (emailRegisterAdmin.getText().length() == 0) {
            addPlaceholderStyle(emailRegisterAdmin);
            emailRegisterAdmin.setText("Email");
        }
    }//GEN-LAST:event_emailRegisterAdminFocusLost

    private void passwordRegisterAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterAdminFocusGained
        // TODO add your handling code here:
        if (passwordRegisterAdmin.getText().equals("Password")) {
            passwordRegisterAdmin.setText("");
            passwordRegisterAdmin.requestFocus();
            passwordRegisterAdmin.setEchoChar('*');
            removePlaceholderStyle(passwordRegisterAdmin);
        }
    }//GEN-LAST:event_passwordRegisterAdminFocusGained

    private void passwordRegisterAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterAdminFocusLost
        // TODO add your handling code here:
         if (passwordRegisterAdmin.getText().length() == 0) {
            addPlaceholderStyle(passwordRegisterAdmin);
            passwordRegisterAdmin.setText("Password");
            passwordRegisterAdmin.setEchoChar((char)0);
        }
    }//GEN-LAST:event_passwordRegisterAdminFocusLost

    private void emailLoginCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailLoginCustomerFocusGained
        // TODO add your handling code here:
        if (emailLoginCustomer.getText().equals("Email")) {
            emailLoginCustomer.setText("");
            emailLoginCustomer.requestFocus();
            removePlaceholderStyle(emailLoginCustomer);
        }
    }//GEN-LAST:event_emailLoginCustomerFocusGained

    private void passwordLoginCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginCustomerFocusLost
        // TODO add your handling code here:
        if (passwordLoginCustomer.getText().length() == 0) {
            addPlaceholderStyle(passwordLoginCustomer);
            passwordLoginCustomer.setText("Password");
            passwordLoginCustomer.setEchoChar((char)0);
        }
    }//GEN-LAST:event_passwordLoginCustomerFocusLost

    private void emailLoginCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailLoginCustomerFocusLost
        // TODO add your handling code here:
        if (emailLoginCustomer.getText().length() == 0) {
            addPlaceholderStyle(emailLoginCustomer);
            emailLoginCustomer.setText("Email");
        }
    }//GEN-LAST:event_emailLoginCustomerFocusLost

    private void passwordLoginCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginCustomerFocusGained
        // TODO add your handling code here:
        if (passwordLoginCustomer.getText().equals("Password")) {
            passwordLoginCustomer.setText("");
            passwordLoginCustomer.requestFocus();
            passwordLoginCustomer.setEchoChar('*');
            removePlaceholderStyle(passwordLoginCustomer);
        }
    }//GEN-LAST:event_passwordLoginCustomerFocusGained

    private void namaRegisterCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaRegisterCustomerFocusGained
        // TODO add your handling code here:
        if (namaRegisterCustomer.getText().equals("Nama Lengkap")) {
            namaRegisterCustomer.setText("");
            namaRegisterCustomer.requestFocus();
            removePlaceholderStyle(namaRegisterCustomer);
        }
    }//GEN-LAST:event_namaRegisterCustomerFocusGained

    private void namaRegisterCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaRegisterCustomerFocusLost
        // TODO add your handling code here:
        if (namaRegisterCustomer.getText().length() == 0) {
            addPlaceholderStyle(namaRegisterCustomer);
            namaRegisterCustomer.setText("Nama Lengkap");
        }
    }//GEN-LAST:event_namaRegisterCustomerFocusLost

    private void emailRegisterCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailRegisterCustomerFocusGained
        // TODO add your handling code here:
        if (emailRegisterCustomer.getText().equals("Email")) {
            emailRegisterCustomer.setText("");
            emailRegisterCustomer.requestFocus();
            removePlaceholderStyle(emailRegisterCustomer);
        }
    }//GEN-LAST:event_emailRegisterCustomerFocusGained

    private void emailRegisterCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailRegisterCustomerFocusLost
        // TODO add your handling code here:
        if (emailRegisterCustomer.getText().length() == 0) {
            addPlaceholderStyle(emailRegisterCustomer);
            emailRegisterCustomer.setText("Email");
        }
    }//GEN-LAST:event_emailRegisterCustomerFocusLost

    private void passwordRegisterCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterCustomerFocusGained
        // TODO add your handling code here:
        if (passwordRegisterCustomer.getText().equals("Password")) {
            passwordRegisterCustomer.setText("");
            passwordRegisterCustomer.requestFocus();
            passwordRegisterCustomer.setEchoChar('*');
            removePlaceholderStyle(passwordRegisterCustomer);
        }
    }//GEN-LAST:event_passwordRegisterCustomerFocusGained

    private void passwordRegisterCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterCustomerFocusLost
        // TODO add your handling code here:
        if (passwordRegisterCustomer.getText().length() == 0) {
            addPlaceholderStyle(passwordRegisterCustomer);
            passwordRegisterCustomer.setText("Password");
            passwordRegisterCustomer.setEchoChar((char)0);
        }
    }//GEN-LAST:event_passwordRegisterCustomerFocusLost

    private void registerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerAdminActionPerformed
        // TODO add your handling code here:
        if (namaRegisterAdmin.getText().equals("Nama Lengkap") || emailRegisterAdmin.getText().equals("Email") || passwordRegisterAdmin.getText().equals("Password")) {
            JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data Diri", "Register", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                akun = new Register (emailRegisterAdmin.getText(), passwordRegisterAdmin.getText(), namaRegisterAdmin.getText());
                if (akun instanceof Register) {
                    register = (Register) akun;
                }
                String sql = "INSERT INTO akunadmin VALUES ('" + register.getNamaLengkap() + "','" + register.getEmail() +  "','" + register.getPassword() + "')";   
                java.sql.Connection connection = (Connection) Koneksi.konfigDB();
                java.sql.PreparedStatement pstm = connection.prepareStatement(sql);
                pstm.execute();
                namaRegisterAdmin.setText("Nama Lengkap");
                emailRegisterAdmin.setText("Email");
                passwordRegisterAdmin.setText("Password");
                JOptionPane.showMessageDialog(null, "Registreasi Berhasil", "Messagge", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Username ini sudah digunakan", "Warning", JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_registerAdminActionPerformed

    private void loginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAdminActionPerformed
        // TODO add your handling code here:
        try {
            akun = new Login(emailLoginAdmin.getText(), passwordLoginAdmin.getText());
            if (akun instanceof Login) {
                login = (Login) akun;
            }
            String sql = "SELECT * FROM akunadmin WHERE email='"+ login.getEmail() +"' AND password='" + login.getPassword() +  "'";
            java.sql.Connection connection = (Connection) Koneksi.konfigDB();
            java.sql.Statement stm = connection.createStatement();
            java.sql.ResultSet result = stm.executeQuery(sql);
            if (result.next()) {
                if (login.getEmail().equals(result.getString("email")) && login.getPassword().equals(result.getString("password"))) {
                    emailLoginAdmin.setText("Email");
                    passwordLoginAdmin.setText("Password");
                    String name = result.getString("nama");
                    String tanggalNow = formatTanggal.format(tanggal);
                    JOptionPane.showMessageDialog(null, "Login Success Sebagai Admin", "Massage", JOptionPane.INFORMATION_MESSAGE); 
                    try {
                        String sqlA = "INSERT INTO historylogin VALUES ('" + name + "','" + login.getEmail() +  "','" + login.getPassword() + "','" + tanggalNow + "')";   
                        java.sql.Connection conn = (Connection) Koneksi.konfigDB();
                        java.sql.PreparedStatement pstm = conn.prepareStatement(sqlA);
                        pstm.execute();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
                    }
                    this.dispose();
                    new HalamanAdmin().setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pastikan username dan password yang anda masukan benar!", "Login", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_loginAdminActionPerformed

    private void RegisterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerActionPerformed
        // TODO add your handling code here:
         if (namaRegisterCustomer.getText().equals("Nama Lengkap") || emailRegisterCustomer.getText().equals("Email") || passwordRegisterCustomer.getText().equals("Password")) {
            JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data Diri", "Register", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                akun = new Register (emailRegisterCustomer.getText(), passwordRegisterCustomer.getText(), namaRegisterCustomer.getText());
                if (akun instanceof Register) {
                    register = (Register) akun;
                }
                String sql = "INSERT INTO akuncustomer VALUES ('" + register.getNamaLengkap() + "','" + register.getEmail() +  "','" + register.getPassword() + "')";   
                java.sql.Connection connection = (Connection) Koneksi.konfigDB();
                java.sql.PreparedStatement pstm = connection.prepareStatement(sql);
                pstm.execute();
                namaRegisterCustomer.setText("Nama Lengkap");
                emailRegisterCustomer.setText("Email");
                passwordRegisterCustomer.setText("Password");
                JOptionPane.showMessageDialog(null, "Registreasi Berhasil", "Messagge", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Username ini sudah digunakan", "Warning", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_RegisterCustomerActionPerformed

    private void loginCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCustomerActionPerformed
        // TODO add your handling code here:
        try {
            akun = new Login(emailLoginCustomer.getText(), passwordLoginCustomer.getText());
            if (akun instanceof Login) {
                login = (Login) akun;
            }
            String sql = "SELECT * FROM akuncustomer WHERE email='"+ login.getEmail() +"' AND password='" + login.getPassword() +  "'";
            java.sql.Connection connection = (Connection) Koneksi.konfigDB();
            java.sql.Statement stm = connection.createStatement();
            java.sql.ResultSet result = stm.executeQuery(sql);
            if (result.next()) {
                if (login.getEmail().equals(result.getString("email")) && login.getPassword().equals(result.getString("password"))) {
                    emailLoginCustomer.setText("Email");
                    passwordLoginCustomer.setText("Password");
                    String name = result.getString("nama");
                    String tanggalNow = formatTanggal.format(tanggal);
                    JOptionPane.showMessageDialog(null, "Login Success Sebagai Customer", "Massage", JOptionPane.INFORMATION_MESSAGE); 
                    try {
                        String sqlA = "INSERT INTO historylogin VALUES ('" + name + "','" + login.getEmail() +  "','" + login.getPassword() + "','" + tanggalNow + "')";   
                        java.sql.Connection conn = (Connection) Koneksi.konfigDB();
                        java.sql.PreparedStatement pstm = conn.prepareStatement(sqlA);
                        pstm.execute();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
                    }
                    this.dispose();
                    new HalamanCustomer().setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pastikan username dan password yang anda masukan benar!", "Login", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_loginCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterCustomer;
    private javax.swing.JPanel activity;
    private javax.swing.JButton backLoginAdmin;
    private javax.swing.JButton backLoginCustomer;
    private javax.swing.JTextField emailLoginAdmin;
    private javax.swing.JTextField emailLoginCustomer;
    private javax.swing.JTextField emailRegisterAdmin;
    private javax.swing.JTextField emailRegisterCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLayeredPane layerActivity;
    private javax.swing.JLayeredPane layerLoginAdmin;
    private javax.swing.JLayeredPane layerLoginCustomer;
    private javax.swing.JLayeredPane layerRegisterAdmin;
    private javax.swing.JLayeredPane layerRegisterCustomer;
    private javax.swing.JButton loginAdmin;
    private javax.swing.JButton loginCustomer;
    private javax.swing.JLabel loginNowAdmin;
    private javax.swing.JLabel loginNowCustomer;
    private javax.swing.JTextField namaRegisterAdmin;
    private javax.swing.JTextField namaRegisterCustomer;
    private javax.swing.JPasswordField passwordLoginAdmin;
    private javax.swing.JPasswordField passwordLoginCustomer;
    private javax.swing.JPasswordField passwordRegisterAdmin;
    private javax.swing.JPasswordField passwordRegisterCustomer;
    private javax.swing.JButton registerAdmin;
    private javax.swing.JLabel registerNowAdmin;
    private javax.swing.JLabel registerNowCustomer;
    private javax.swing.JButton selectAdmin;
    private javax.swing.JButton selectCustomer;
    // End of variables declaration//GEN-END:variables
}
