/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import oop.Register;

/**
 *
 * @author User
 */
public class HalamanCustomer extends javax.swing.JFrame{

    /**
     * Creates new form HalamanCustomer
     */


    String kode = "";
    private static final File file = new File("src/sound/backsound.wav");
    private AudioInputStream audioInputStream;
    private Clip clip;


    public HalamanCustomer() {
        initComponents();
        try {
            audioInputStream = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
        addPlaceholderStyle(tipeHandpone);
        addPlaceholderStyle(alamatLengkap);
        addPlaceholderStyle(masalahHandpone);
        buttonMusicOn.setVisible(false);
        buttonMusicOff.setVisible(true);
        prosesBar.setStringPainted(true);
    }
    
    public String kodeService(int n) {
        Random random = new Random(62);
        String character = "0123456789";

        String kode = "";
        while (n-- > 0) {
            int index = (int) (Math.random() * 9);
            kode += character.charAt(index);
        }
        return "IS" + kode;
    }

    public void addPlaceholderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.BLACK);
    }
    
    public void removePlaceholderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
    public void addPlaceholderStyle(JTextArea textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.BLACK);
    }
    
    public void removePlaceholderStyle(JTextArea textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logoutHalamanCustomer = new javax.swing.JButton();
        layerService = new javax.swing.JLayeredPane();
        jPanel7 = new javax.swing.JPanel();
        tipeHandpone = new javax.swing.JTextField();
        jenisHandpone = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        masalahHandpone = new javax.swing.JTextArea();
        alamatLengkap = new javax.swing.JTextField();
        buttonProsesPesanan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        prosesBar = new javax.swing.JProgressBar();
        buttonMusicOn = new javax.swing.JButton();
        buttonMusicOff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/servis.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 240));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 4, 449));

        logoutHalamanCustomer.setBackground(new java.awt.Color(255, 0, 51));
        logoutHalamanCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutHalamanCustomer.setForeground(new java.awt.Color(255, 255, 255));
        logoutHalamanCustomer.setText("Logout");
        logoutHalamanCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutHalamanCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(logoutHalamanCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 200, 25));

        jPanel7.setBackground(new java.awt.Color(0, 204, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipeHandpone.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tipeHandpone.setText("Tipe Handpone");
        tipeHandpone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tipeHandponeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipeHandponeFocusLost(evt);
            }
        });
        jPanel7.add(tipeHandpone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 270, 25));

        jenisHandpone.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jenisHandpone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Handpone", "Android", "IOS" }));
        jPanel7.add(jenisHandpone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 270, 25));

        masalahHandpone.setColumns(20);
        masalahHandpone.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        masalahHandpone.setRows(5);
        masalahHandpone.setText("Masalah Handpone");
        masalahHandpone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                masalahHandponeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                masalahHandponeFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(masalahHandpone);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 270, 80));

        alamatLengkap.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        alamatLengkap.setText("Alamat Lengkap");
        alamatLengkap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alamatLengkapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                alamatLengkapFocusLost(evt);
            }
        });
        jPanel7.add(alamatLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 270, 25));

        buttonProsesPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonProsesPesanan.setText("Proses Pesanan");
        buttonProsesPesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        buttonProsesPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesPesananActionPerformed(evt);
            }
        });
        jPanel7.add(buttonProsesPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 190, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WELCOME I SERVICE");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, 70));

        prosesBar.setBackground(new java.awt.Color(0, 51, 255));
        prosesBar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        prosesBar.setOpaque(true);
        jPanel7.add(prosesBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 270, 20));

        layerService.setLayer(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layerServiceLayout = new javax.swing.GroupLayout(layerService);
        layerService.setLayout(layerServiceLayout);
        layerServiceLayout.setHorizontalGroup(
            layerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );
        layerServiceLayout.setVerticalGroup(
            layerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        jPanel1.add(layerService, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 5, -1, 440));

        buttonMusicOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sound on.png"))); // NOI18N
        buttonMusicOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMusicOnActionPerformed(evt);
            }
        });
        jPanel1.add(buttonMusicOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 54, 55));

        buttonMusicOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sound off.png"))); // NOI18N
        buttonMusicOff.setMaximumSize(new java.awt.Dimension(54, 55));
        buttonMusicOff.setMinimumSize(new java.awt.Dimension(54, 55));
        buttonMusicOff.setPreferredSize(new java.awt.Dimension(54, 55));
        buttonMusicOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMusicOffActionPerformed(evt);
            }
        });
        jPanel1.add(buttonMusicOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 54, 55));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tipeHandponeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipeHandponeFocusGained
        // TODO add your handling code here:
        if (tipeHandpone.getText().equals("Tipe Handpone")) {
            tipeHandpone.setText("");
            tipeHandpone.requestFocus();
            removePlaceholderStyle(tipeHandpone);
        }
    }//GEN-LAST:event_tipeHandponeFocusGained

    private void tipeHandponeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipeHandponeFocusLost
        // TODO add your handling code here:
         if (tipeHandpone.getText().length() == 0) {
            addPlaceholderStyle(tipeHandpone);
            tipeHandpone.setText("Tipe Handpone");
        }
    }//GEN-LAST:event_tipeHandponeFocusLost

    private void alamatLengkapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alamatLengkapFocusGained
        // TODO add your handling code here:
         if (alamatLengkap.getText().equals("Alamat Lengkap")) {
            alamatLengkap.setText("");
            alamatLengkap.requestFocus();
            removePlaceholderStyle(alamatLengkap);
        }
    }//GEN-LAST:event_alamatLengkapFocusGained

    private void alamatLengkapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alamatLengkapFocusLost
        // TODO add your handling code here:
        if (alamatLengkap.getText().length() == 0) {
            addPlaceholderStyle(alamatLengkap);
            alamatLengkap.setText("Alamat Lengkap");
        }
    }//GEN-LAST:event_alamatLengkapFocusLost

    private void masalahHandponeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_masalahHandponeFocusGained
        // TODO add your handling code here:
         if (masalahHandpone.getText().equals("Masalah Handpone")) {
            masalahHandpone.setText("");
            masalahHandpone.requestFocus();
            removePlaceholderStyle(masalahHandpone);
        }
    }//GEN-LAST:event_masalahHandponeFocusGained

    private void masalahHandponeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_masalahHandponeFocusLost
        // TODO add your handling code here:
        if (masalahHandpone.getText().length() == 0) {
            addPlaceholderStyle(masalahHandpone);
            masalahHandpone.setText("Masalah Handpone");
        }
    }//GEN-LAST:event_masalahHandponeFocusLost

    private void logoutHalamanCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutHalamanCustomerActionPerformed
        // TODO add your handling code here:
        clip.stop();
        this.dispose();
        new HalamanLogin().setVisible(true);
    }//GEN-LAST:event_logoutHalamanCustomerActionPerformed
 
    private void buttonProsesPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesPesananActionPerformed
        // TODO add your handling code here:
        if (jenisHandpone.getSelectedIndex() == 0 || tipeHandpone.getText().equals("Tipe Handpone")|| alamatLengkap.getText().equals("Alamat Lengkap") || masalahHandpone.getText().equals("Masalah Handpone")) {
            JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data Service", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            int count = 0;
            kode = kodeService(3);
            try {
                String sqlB = "SELECT * FROM dataservice";
                java.sql.Connection conn = (Connection) Koneksi.konfigDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet result = stm.executeQuery(sqlB);
                while (result.next()) {
                    if (kode.equals(result.getString("kodeservice"))) {
                        kode = kodeService(1);
                    } else {
                        break;
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            while (count <= 100) {
                prosesBar.setValue(count);
                try {
                    Thread.sleep(200);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
                prosesBar.setValue(count);
                count += 10;
            }
            prosesBar.setBackground(Color.blue);
            prosesBar.setString("100 %");
            try {
                String sql = "INSERT INTO dataservice VALUES ('" + kode  + "','" + jenisHandpone.getSelectedItem() +  "','" +tipeHandpone.getText() +  "','" + alamatLengkap.getText() + "','" + masalahHandpone.getText() + "','" + "Sedang Diproses" +"')";   
                java.sql.Connection connection = (Connection) Koneksi.konfigDB();
                java.sql.PreparedStatement pstm = connection.prepareStatement(sql);
                pstm.execute();
                jenisHandpone.setSelectedIndex(0);
                tipeHandpone.setText("Tipe Handpone");
                alamatLengkap.setText("Alamat Lengkap");
                masalahHandpone.setText("Masalah Handpone");
                buttonProsesPesanan.setText("Pesanan Berhasil Diproses");
                buttonProsesPesanan.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Pesanan Berhasil Diproses", "Messagge", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonProsesPesananActionPerformed

    private void buttonMusicOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMusicOffActionPerformed
        // TODO add your handling code here:
        buttonMusicOff.setVisible(false);
        buttonMusicOn.setVisible(true);
        clip.stop();
    }//GEN-LAST:event_buttonMusicOffActionPerformed

    private void buttonMusicOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMusicOnActionPerformed
        // TODO add your handling code here:
        buttonMusicOff.setVisible(true);
        buttonMusicOn.setVisible(false);
        clip.start();
    }//GEN-LAST:event_buttonMusicOnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanCustomer().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatLengkap;
    private javax.swing.JButton buttonMusicOff;
    private javax.swing.JButton buttonMusicOn;
    private javax.swing.JButton buttonProsesPesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisHandpone;
    private javax.swing.JLayeredPane layerService;
    private javax.swing.JButton logoutHalamanCustomer;
    private javax.swing.JTextArea masalahHandpone;
    private javax.swing.JProgressBar prosesBar;
    private javax.swing.JTextField tipeHandpone;
    // End of variables declaration//GEN-END:variables

}
